### PR TITLE
Using pandas' on-the-fly decompression

### PR DESCRIPTION
**Pull request by Moohan**
It may actually make more sense to drop pandas in favour of standard packages, to reduce the requirements...

### CODE REVIEW

**Comment by jankais3r** [comment]
I am worried that some people might run out of RAM during this operation when running on an older raspberry pi… I'll look into it, thanks for the PR.

**Comment by dwightmulcahy** [comment]
Yeah, I didn't look into the error but checking out this branch on a raspberry pi 2B it errored out with "Import failed. Quitting."

**Comment by TrueDolphin** [comment]
I've got this and pi-hole running on:
Pi Model B Revision 2.0
Pi 2 model B+
Pi 3 model B+
Pi-hole logs are more of a concern than the ram usage of this.
Jankais3r, if you want me to test anything for you, lemme know.

**Comment by jankais3r** [comment]
I did some testing and the RAM usage actually seems lower compared to manually extracting the CSV prior to import. The exception is caused by a row that tries to delete the now non-existent CSV file that @Moohan forgot to remove. I'll fix that myself. Thanks for the PR.

**Pull request merged**
